/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: process.env.SITE_URL || 'https://www.techblit.com',
  // robots.txt is generated by the Next metadata route at src/app/robots.ts
  // (it also links the Google News sitemap). Keep next-sitemap out of it so
  // the two don't fight over public/robots.txt.
  generateRobotsTxt: false,
  generateIndexSitemap: false,
  // /newsletter/* URLs carry one-time confirm and per-subscriber
  // unsubscribe tokens — they must never be crawled or indexed.
  exclude: ['/admin/*', '/api/*', '/newsletter/*'],
};
